baseURL: http://something-fresh.org/
languageCode: en-us
title: Plantly | Serverless smart plants
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Grow your plants, anywhere.
    # Hero subtitle (optional)
    subtitle: Track the status of your plants on the go.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: https://plantly.netlify.app/
    # Hero image (from static/images/___)
    image: illustrations/freelancing.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - aws.svg
    - nextjs.png
    - elasticsearch.png
    - tensorflow.png
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  # - title: Features
  #   url: /
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  - title: Log in
    url: https://plantly.netlify.app/login
  - title: Sign up
    url: https://plantly.netlify.app/register
    button: true
  section1:
    title: Great power comes
    subtitle: with great responsibilities 
    tiles:
    - title: Dashboard
      icon: speedometer
      text: Track your plants growth data visually with a dashboard
      url: https://plantly.netlify.app/
      buttonText: Get started
    - title: Cloud Integration
      icon: database
      text: Seamlessly access your plants data through with cloud
      url: https://aws.amazon.com/
      buttonText: Learn More
    - title: Machine Learning
      icon: ai
      text: Have machine learning do all the hard work for you
      url: https://www.tensorflow.org/ 
      buttonText: Learn more
  section2:
      title: How it works
      subtitle: Plantly is an integrated platform which aims to bring you and your plant into ultimate synchronicity!
      features:
      - title: Plant Health Monitoring
        text: Plantly will monitor your plants health, ensuring that the optimal benchmarks are met to ensure your plant is healthy.
        icon: health
      - title: Predictive Machine Learning Power
        text: Through machine learning, Plantly will autonomously optimise your plants growth through semi autonomously controlling your plants biome.
        icon: ai2
      - title: Live Alerts and Notifications
        text: Plantly also offers a dashboard where you can visually view your plants health. Plantly will also send you notifications of your plant's health on the go.
        icon: bell 
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: https://plantly.netlify.app/
  section4: 
    heading: Meet the team!
    subheading: We are a group of RMIT Students who are interested in shaping the ecosystem
    tiles: 
    - name: Thang Pham
      face: austin.jpg
      icon: github
      url: https://github.com/rockmanvnx6
      icon2: linkedin
      url2: https://www.linkedin.com/in/pnt263/
    - name: Duy Nguyen
      face: linh.jpg
      icon: github
      url: https://github.com/nugyn
      icon2: linkedin
      url2: https://www.linkedin.com/in/duy-linh-nguyen/
    - name: Inci Keleher
      face: inci.jpg
      icon: github
      url: https://github.com/inci90
      icon2: linkedin
      url2: https://www.linkedin.com/in/isaac-keleher/
    - name: Don Phu
      face: don.jpg
      icon: github
      url: https://github.com/DonneyDucka
      icon2: linkedin
      url2: https://www.linkedin.com/in/donphu/
    - name: Duy Vo
      face: david.jpg
      icon: github
      url: https://github.com/thedavidvo
      icon2: linkedin
      url2: https://www.linkedin.com/in/duyyvo/
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: logo-white.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/PGP1/pgp1.github.io
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Sponsored by"
        links:
        - text: RMIT University
          link: https://www.rmit.edu.au/
        - text: Amir Ashrafzadeh
          link: /
        # - text: Compare features
        #   link: /
        # - text: Our roadmap
        #   link: /
        # - text: AGB
        #   link: /agb
      column2:
        title: "About the company"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
